// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using NoveduBackend.Persistence.Util;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoveduBackend.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260511081351_ErdV2")]
    partial class ErdV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("NoveduBackend")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoveduBackend.Persistence.Model.AiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerMillionCachedInputTokens")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal>("CostPerMillionInputTokens")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<decimal>("CostPerMillionOutputTokens")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxInputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendationTag")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("AiModel", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.AiProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AiProvider", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.BudgetConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("WarningThreshold")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("BudgetConfig", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.BudgetUsagePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetConfigId")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("EndDate")
                        .HasColumnType("date");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BudgetConfigId");

                    b.HasIndex("UserId");

                    b.ToTable("BudgetUsagePeriod", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("UserId");

                    b.ToTable("Chat", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.ChatAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("ChatAttachment", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.CostEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetUsagePeriodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BudgetUsagePeriodId");

                    b.HasIndex("MessageId");

                    b.HasIndex("TutorId");

                    b.ToTable("CostEntry", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("SchoolId")
                        .IsUnique();

                    b.ToTable("GlobalSettings", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetConfigId")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GroupTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetConfigId");

                    b.HasIndex("GroupTypeId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Group", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMember", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.GroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GroupType", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Message", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.MessageMonitoringFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<Instant?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("MessageMonitoringFlag", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetConfigId")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetConfigId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Role", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("School", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.SchoolAiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("SchoolId", "ModelId")
                        .IsUnique();

                    b.ToTable("SchoolAiModel", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.SchoolAiProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SchoolId", "ProviderId")
                        .IsUnique();

                    b.ToTable("SchoolAiProvider", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.SchoolEntraConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientSecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .IsUnique();

                    b.ToTable("SchoolEntraConfig", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Subject", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorCollaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SharedById")
                        .HasColumnType("integer");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SharedById");

                    b.HasIndex("UserId");

                    b.HasIndex("TutorId", "GroupId")
                        .IsUnique();

                    b.HasIndex("TutorId", "UserId")
                        .IsUnique();

                    b.ToTable("TutorCollaborator", "NoveduBackend", t =>
                        {
                            t.HasCheckConstraint("CK_TutorCollaborator_UserOrGroup", "(\"UserId\" IS NOT NULL AND \"GroupId\" IS NULL) OR (\"UserId\" IS NULL AND \"GroupId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnonymizePii")
                        .HasColumnType("boolean");

                    b.Property<int?>("CopiedFromId")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultInternalPermission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DidacticMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HideKnowledgeBase")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("ShowSources")
                        .HasColumnType("boolean");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CopiedFromId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TutorConfig", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("LastUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorDocument", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorGroupAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedById")
                        .HasColumnType("integer");

                    b.Property<int?>("BudgetConfigId")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("EnabledFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("EnabledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("BudgetConfigId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TutorId", "GroupId")
                        .IsUnique();

                    b.ToTable("TutorGroupAssignment", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorStudentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("EnabledFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("EnabledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TutorId", "UserId")
                        .IsUnique();

                    b.ToTable("TutorStudentAssignment", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetConfigId")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("EntraOid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetConfigId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraOid")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("SchoolId");

                    b.ToTable("User", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("NotifyBudgetWarning")
                        .HasColumnType("boolean");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", "NoveduBackend");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.AiModel", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.AiProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.BudgetUsagePeriod", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.BudgetConfig", "BudgetConfig")
                        .WithMany("UsagePeriods")
                        .HasForeignKey("BudgetConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.User", "User")
                        .WithMany("BudgetUsagePeriods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Chat", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "Tutor")
                        .WithMany("Chats")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tutor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.ChatAttachment", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.CostEntry", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.BudgetUsagePeriod", "BudgetUsagePeriod")
                        .WithMany("CostEntries")
                        .HasForeignKey("BudgetUsagePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.Message", "Message")
                        .WithMany("CostEntries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "Tutor")
                        .WithMany("CostEntries")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetUsagePeriod");

                    b.Navigation("Message");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.GlobalSettings", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithOne("GlobalSettings")
                        .HasForeignKey("NoveduBackend.Persistence.Model.GlobalSettings", "SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastModifiedBy");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Group", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.BudgetConfig", "BudgetConfig")
                        .WithMany()
                        .HasForeignKey("BudgetConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoveduBackend.Persistence.Model.GroupType", "GroupType")
                        .WithMany("Groups")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithMany("Groups")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetConfig");

                    b.Navigation("GroupType");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.GroupMember", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Message", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.MessageMonitoringFlag", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.Message", "Message")
                        .WithMany("MonitoringFlags")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.User", "ReviewedBy")
                        .WithMany("ReviewedMonitoringFlags")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Message");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Role", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.BudgetConfig", "BudgetConfig")
                        .WithMany()
                        .HasForeignKey("BudgetConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithMany("Roles")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetConfig");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.SchoolAiModel", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.AiModel", "Model")
                        .WithMany("SchoolAiModels")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithMany("SchoolAiModels")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.SchoolAiProvider", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.AiProvider", "Provider")
                        .WithMany("SchoolAiProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithMany("SchoolAiProviders")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.SchoolEntraConfig", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithOne("EntraConfig")
                        .HasForeignKey("NoveduBackend.Persistence.Model.SchoolEntraConfig", "SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Subject", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorCollaborator", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.Group", "Group")
                        .WithMany("TutorCollaborations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NoveduBackend.Persistence.Model.User", "SharedBy")
                        .WithMany("SharedTutorCollaborations")
                        .HasForeignKey("SharedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "Tutor")
                        .WithMany("Collaborators")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.User", "User")
                        .WithMany("TutorCollaborations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");

                    b.Navigation("SharedBy");

                    b.Navigation("Tutor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorConfig", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "CopiedFrom")
                        .WithMany("Copies")
                        .HasForeignKey("CopiedFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoveduBackend.Persistence.Model.User", "CreatedBy")
                        .WithMany("CreatedTutors")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.AiModel", "Model")
                        .WithMany("Tutors")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.Subject", "Subject")
                        .WithMany("Tutors")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CopiedFrom");

                    b.Navigation("CreatedBy");

                    b.Navigation("Model");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorDocument", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "Tutor")
                        .WithMany("Documents")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorGroupAssignment", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.User", "AssignedBy")
                        .WithMany("TutorGroupAssignmentsMade")
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.BudgetConfig", "BudgetConfig")
                        .WithMany("TutorGroupAssignments")
                        .HasForeignKey("BudgetConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoveduBackend.Persistence.Model.Group", "Group")
                        .WithMany("TutorAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "Tutor")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("BudgetConfig");

                    b.Navigation("Group");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorStudentAssignment", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.TutorConfig", "Tutor")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.User", "User")
                        .WithMany("TutorAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.User", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.BudgetConfig", "BudgetConfig")
                        .WithMany()
                        .HasForeignKey("BudgetConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoveduBackend.Persistence.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoveduBackend.Persistence.Model.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetConfig");

                    b.Navigation("Role");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.UserSettings", b =>
                {
                    b.HasOne("NoveduBackend.Persistence.Model.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("NoveduBackend.Persistence.Model.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.AiModel", b =>
                {
                    b.Navigation("SchoolAiModels");

                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.AiProvider", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("SchoolAiProviders");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.BudgetConfig", b =>
                {
                    b.Navigation("TutorGroupAssignments");

                    b.Navigation("UsagePeriods");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.BudgetUsagePeriod", b =>
                {
                    b.Navigation("CostEntries");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TutorAssignments");

                    b.Navigation("TutorCollaborations");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.GroupType", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CostEntries");

                    b.Navigation("MonitoringFlags");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.School", b =>
                {
                    b.Navigation("EntraConfig");

                    b.Navigation("GlobalSettings");

                    b.Navigation("Groups");

                    b.Navigation("Roles");

                    b.Navigation("SchoolAiModels");

                    b.Navigation("SchoolAiProviders");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.Subject", b =>
                {
                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.TutorConfig", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Collaborators");

                    b.Navigation("Copies");

                    b.Navigation("CostEntries");

                    b.Navigation("Documents");

                    b.Navigation("GroupAssignments");

                    b.Navigation("StudentAssignments");
                });

            modelBuilder.Entity("NoveduBackend.Persistence.Model.User", b =>
                {
                    b.Navigation("BudgetUsagePeriods");

                    b.Navigation("Chats");

                    b.Navigation("CreatedTutors");

                    b.Navigation("GroupMemberships");

                    b.Navigation("ReviewedMonitoringFlags");

                    b.Navigation("Settings");

                    b.Navigation("SharedTutorCollaborations");

                    b.Navigation("TutorAssignments");

                    b.Navigation("TutorCollaborations");

                    b.Navigation("TutorGroupAssignmentsMade");
                });
#pragma warning restore 612, 618
        }
    }
}
