= LLM Gateway Comparison
== LiteLLM vs OpenRouter vs possible own solution
:author: Novedu
:toc:
:toc-title: Table of Contents

== Evaluation Criteria

* Privacy
- Self-hostable, otherwise Server must be in the European Union, no model training on user data
* Pricing & Budget Control
- Transparent Model Pricing, Token/Cost Tracking per class, Budget Limits
* Ease of Integration
- Clear docs, simple rest api
* Model Diversity
- Mandatory: Azure OpenAI; optional: OpenAI, Claude, Gemini, Mistral

== 1. LiteLLM

=== Privacy

LiteLLM can be self-hosted, (e.g., on Azure).
When self-hosted, all data stays within the own infrastructure.
LiteLLM does not train models on user data.

=== Pricing & Budget Control

LiteLLM provides flexible cost tracking and pricing customization for all LLM providers.
You can choose either custom pricing where you override default model costs or use the most common option _cost per token_.
In LiteLLM, you can also set budgets for your API requests using tags.
Tags are labels you can attach to your request to track and limit spending by category.
With this feature, you could filter requests by class, which allows us to have token/cost tracking per class and set budget limits accordingly.

=== Ease of Integration

LiteLLM offers a clear documentation on their own website, as for the proxy server and also for the SDKs.
If you set it up as a proxy, you have a lot of initial work to do, but once done, integration is straightforward via REST API.

=== Model Diversity

LiteLLM supports over 100 models from multiple providers, including all of our mandatory and optional providers and a lot more

== 2. OpenRouter

=== Privacy

OpenRouter is a fully managed SaaS footnote:[Software as a Service; cloud-hosted application accessed over the internet.]
solution.
All requests are processed through OpenRouter servers.
To have your requests routed through a European server, you must subscribe to the Enterprise plan.
OpenRouter does not train models on user data, but it samples a small number of prompts for anonymized categorization to power reporting and model ranking.
OpenRouter does not provide an option to self-host the gateway.

=== Pricing & Budget Control

OpenRouter charges a 5.5% fee when purchasing credits.
They pass through the pricing of the underlying LLM providers.
Concerning cost tracking, you have two options: If you like, you can use a dashboard to track usage and spending by Provider/Model.
Alternatively, you can enable usage accounting for your API requests.
When you add the usage parameter, OpenRouter will return a usage object with detailed token information.
LiteLLM does not provide budget limit features, you would have to implement this on your side.

=== Ease of Integration

OpenRouter provides a quickstart guide and API documentation on their website.
Because it's a fully managed SaaS solution, you don't have to set up any infrastructure.
Integration is straightforward via REST API.

=== Model Diversity

OpenRouter supports over 300 models from more than 60 providers, including all of our mandatory and optional providers.

== 3. Other considerations

=== Cloudflare AI Gateway

It offers a wide range of models, easy integration, and an appealing dashboard.
While it supports rate limiting to control usage, it lacks more advanced budget management features (as budget per class).
Additionally, as a SaaS service, it is not possible for us to determine exactly where data is processed.

=== Own Solution

==== Benefits
You have full control over your infrastructure, meaning you can tailor the gateway to your requirements.
It's possible to implement custom features that may not be available in LiteLLM or OpenRouter. +
You can also have a tighter integration with your existing system (and e.g. use existing authentication mechanisms). +
If, for example, LiteLLM has an outage, you wouldn't be able to use it until it's back online.
With your own solution,
you can ensure high availability because you are in charge of when the maintenance works take place.

==== Development
Building your own LLM gateway requires significant development effort and expertise.
It takes at least 6 months to have a minimal viable product (MVP).
Furthermore, you have to continue with observability.
This means you need to monitor the system, track data (e.g. response times), and summarize your findings. +
You also have to validate outputs and avoid the AI to generate harmful content. +

It is very hard to work on such a project without prior experience.
You must be familiar with LLMs, APIs, security best practices, and coding in general, of course.
It is also good to know about CI/CD pipelines, containerization (e.g., Docker), and orchestration (e.g., Kubernetes).

==== Maintenance Overhead
Maintaining your own LLM gateway involves a lot of ongoing tasks.
If you use multiple LLM providers, you have to keep track of their API changes and update your gateway accordingly.
You need to manage API keys, tokens, and user access securely to ensure nothing gets compromised.
Requests must be distributed across multiple providers or instances,
which means you need to monitor system performance and availability.
You also have to enforce rate limits to match the constraints of each provider.
Last but not least, you have to log requests, responses, and system events securely for auditing and debugging purposes.

// == Pricing

// See https://www.litellm.ai/#pricing for LiteLLM pricing details and https://openrouter.ai/pricing for OpenRouter pricing details.

// === OpenRouter Pricing

// OpenRouter offers a free tier with slightly more than 25 Models.
// If you want more Models, you need to subscribe to a "Pay-as-you-go" plan.
// It provides around 300 Models for a platform fee of 5.5% on top of model cost.
// You can buy enterprise plans for more features (price on request).

// === LiteLLM Pricing

// LiteLLM's free plan provides around 100 Models.
// They also offer an "Enterprise" plan with additional features (price on request).

// == Feature Comparison

// The following table summarizes key features of LiteLLM and OpenRouter to give a quick overview of their capabilities.

// [cols="1,1",options="header"]
// |===
// | LiteLLM | OpenRouter
// | Supports 100+ models via multiple providers
// | Supports 300+ models from ~50 providers
// | self-hostable (Docker/K8s), full control over infrastructure| Fully Managed SaaS; no need to run your own gateway infrastructure
// | Data stays inside your infrastructure when self-hosted
// | Requests processed through OpenRouter servers

// |===

Sources +
https://www.reddit.com/r/LocalLLaMA/comments/1l98lly/privacy_implications_of_sending_data_to_openrouter/[Privacy Implications of using OpenRouter] +

https://docs.litellm.ai/docs/proxy/custom_pricing[LiteLLM Custom Pricing] +
https://www.litellm.ai/[LiteLLM Website] +
https://docs.litellm.ai/docs/proxy/tag_budgets[LiteLLM Tag Budgets] +
https://docs.litellm.ai/[LiteLLM Getting Started] +
https://models.litellm.ai/[LiteLLM Model List] +

https://openrouter.ai/[OpenRouter website] +
https://openrouter.ai/docs/guides/guides/usage-accounting[OpenRouter Usage Accounting] +
https://openrouter.ai/activity[OpenRouter Activity Dashboard] +
https://openrouter.ai/docs/quickstart[OpenRouter Quickstart Guide] +
https://openrouter.ai/pricing[OpenRouter Pricing (see Models section)]

https://developers.cloudflare.com/ai-gateway/usage/providers/[Cloudflare AI Gateway Supported Models] +
https://developers.cloudflare.com/ai-gateway/[Cloudflare AI Gateway Documentation] +

https://portkey.ai/blog/the-cost-of-building-an-llm-gateway/[The Cost of Building an LLM Gateway]